"""Initial schema for visitors, hosts, and visits (PoC).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-19
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  used by autogenerated columns
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "visitors",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_visitors_email", "visitors", ["email"])
    op.create_index("ix_visitors_phone", "visitors", ["phone"])

    op.create_table(
        "hosts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("account_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    op.create_index("ix_hosts_display_name", "hosts", ["display_name"])
    op.create_index("ix_hosts_email", "hosts", ["email"], unique=True)

    op.create_table(
        "visits",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("visitor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("visitors.id"), nullable=False),
        sa.Column("host_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("hosts.id"), nullable=True),
        sa.Column("host_name_raw", sa.String(length=200), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False, server_default="qr_self_checkin"),
        sa.Column("host_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_visits_visitor_id", "visits", ["visitor_id"])
    op.create_index("ix_visits_host_id", "visits", ["host_id"])
    op.create_index("ix_visits_arrived_at", "visits", ["arrived_at"])


def downgrade() -> None:
    op.drop_index("ix_visits_arrived_at", table_name="visits")
    op.drop_index("ix_visits_host_id", table_name="visits")
    op.drop_index("ix_visits_visitor_id", table_name="visits")
    op.drop_table("visits")

    op.drop_index("ix_hosts_email", table_name="hosts")
    op.drop_index("ix_hosts_display_name", table_name="hosts")
    op.drop_table("hosts")

    op.drop_index("ix_visitors_phone", table_name="visitors")
    op.drop_index("ix_visitors_email", table_name="visitors")
    op.drop_table("visitors")
