"""Initial schema for visitors, visits, hosts, consent, integration jobs, audit.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-14
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  used by autogenerated columns
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "visitors",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_visitors_email", "visitors", ["email"])
    op.create_index("ix_visitors_phone", "visitors", ["phone"])

    op.create_table(
        "hosts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("graph_user_id", sa.String(length=128), nullable=True),
        sa.Column("account_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_hosts_display_name", "hosts", ["display_name"])
    op.create_index("ix_hosts_email", "hosts", ["email"], unique=True)
    op.create_index("ix_hosts_graph_user_id", "hosts", ["graph_user_id"])

    op.create_table(
        "visits",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("visitor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("visitors.id"), nullable=False),
        sa.Column("host_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("hosts.id"), nullable=True),
        sa.Column("host_name_raw", sa.String(length=200), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False, server_default="qr_self_checkin"),
        sa.Column("hubspot_contact_id", sa.String(length=64), nullable=True),
        sa.Column("hubspot_note_id", sa.String(length=64), nullable=True),
        sa.Column("hubspot_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("host_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_visits_visitor_id", "visits", ["visitor_id"])
    op.create_index("ix_visits_host_id", "visits", ["host_id"])
    op.create_index("ix_visits_arrived_at", "visits", ["arrived_at"])

    op.create_table(
        "consent_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("visitor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("visitors.id"), nullable=True),
        sa.Column("visit_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("visits.id"), nullable=True),
        sa.Column("consent_type", sa.String(length=64), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("consent_text_version", sa.String(length=64), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
    )

    op.create_table(
        "integration_jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("visit_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("visits.id"), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="pending"),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_integration_jobs_visit_id", "integration_jobs", ["visit_id"])
    op.create_index("ix_integration_jobs_status", "integration_jobs", ["status"])

    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("details", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_audit_events_created_at", "audit_events", ["created_at"])
    op.create_index(
        "ix_audit_events_target_type_target_id",
        "audit_events",
        ["target_type", "target_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_audit_events_target_type_target_id", table_name="audit_events")
    op.drop_index("ix_audit_events_created_at", table_name="audit_events")
    op.drop_table("audit_events")

    op.drop_index("ix_integration_jobs_status", table_name="integration_jobs")
    op.drop_index("ix_integration_jobs_visit_id", table_name="integration_jobs")
    op.drop_table("integration_jobs")

    op.drop_table("consent_events")

    op.drop_index("ix_visits_arrived_at", table_name="visits")
    op.drop_index("ix_visits_host_id", table_name="visits")
    op.drop_index("ix_visits_visitor_id", table_name="visits")
    op.drop_table("visits")

    op.drop_index("ix_hosts_graph_user_id", table_name="hosts")
    op.drop_index("ix_hosts_email", table_name="hosts")
    op.drop_index("ix_hosts_display_name", table_name="hosts")
    op.drop_table("hosts")

    op.drop_index("ix_visitors_phone", table_name="visitors")
    op.drop_index("ix_visitors_email", table_name="visitors")
    op.drop_table("visitors")
